tasks:
  - name: Start PDF Generator
    init: sudo apt update && wget https://github.com/jgm/pandoc/releases/download/2.17.1.1/pandoc-2.17.1.1-1-amd64.deb && sudo dpkg -i pandoc-2.17.1.1-1-amd64.deb && rm -rf pandoc-2.17.1.1-1-amd64.deb && sudo apt install texlive-xetex -y && pip3 install -r requirements.txt
    command: sh ./watch.sh

vscode:
  extensions:
    - notZaki.pandocciter
    - yzhang.markdown-all-in-one
    - akamud.vscode-theme-onedark
    - EditorConfig.EditorConfig
    - PKief.material-icon-theme
    - tomoki1207.pdf
    - valentjn.vscode-ltex
